INSERT INTO `retail_sales_sql` (`Database`) VALUES ('information_schema');
INSERT INTO `retail_sales_sql` (`Database`) VALUES ('mysql');
INSERT INTO `retail_sales_sql` (`Database`) VALUES ('performance_schema');
INSERT INTO `retail_sales_sql` (`Database`) VALUES ('retail_sales');
INSERT INTO `retail_sales_sql` (`Database`) VALUES ('sys');
INSERT INTO `retail_sales_sql` (`DATABASE()`) VALUES ('retail_sales');
INSERT INTO `retail_sales_sql` (`total_sales`) VALUES (2252607.41);
INSERT INTO `retail_sales_sql` (`Region`, `sales`) VALUES ('West', 710219.68);
INSERT INTO `retail_sales_sql` (`Region`, `sales`) VALUES ('East', 660589.36);
INSERT INTO `retail_sales_sql` (`Region`, `sales`) VALUES ('Central', 492646.91);
INSERT INTO `retail_sales_sql` (`Region`, `sales`) VALUES ('South', 389151.46);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('California', 446306.46);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('New York', 306361.15);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('Texas', 168572.53);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('Washington', 135206.85);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('Pennsylvania', 116276.65);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('Florida', 88436.53);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('Illinois', 79236.52);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('Michigan', 76136.07);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('Ohio', 75130.35);
INSERT INTO `retail_sales_sql` (`State`, `sales`) VALUES ('Virginia', 70636.72);
